steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/tic-tac-toe', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/tic-tac-toe']

images:
  - 'gcr.io/$PROJECT_ID/tic-tac-toe'